### ISSUE TITLE
这个算异常吗

### ISSUE THREAD

**Issue by zhan520g** [catcherwong/nacos-sdk-csharp#10]
[client.SendHeartbeat] server return {"code":10200,"lightBeatEnabled":true,"clientBeatInterval":5000} 

查不到"code":10200, 是什么意思， 楼主有相关的资料吗

**Comment by catcherwong** [comment]
这个不算是异常， code 10200 在nacos的源码中是 OK的意思 

https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/common/ResponseCode.java

**Comment by zhan520g** [comment]
> 这个不算是异常， code 10200 在nacos的源码中是 OK的意思
> 
> https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/common/ResponseCode.java
嗯嗯， 应该是nacos版本升级了吧, 之前不返回这个code

**Comment by zhan520g** [comment]
> 这个不算是异常， code 10200 在nacos的源码中是 OK的意思
> 
> https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/common/ResponseCode.java

NACOS1.1.4 --》NACOS1.2.0版本  ，版本更新，导致了偶尔会断。 我们又回到了1.1.4版本

**Comment by xiluzi** [comment]
我也是返回这个，然后发心跳的时候偶尔会断。用的openapi去连的，请问题主也是这种情况吗？

**Comment by catcherwong** [comment]
code 10200  问题已经调整过来了。

https://github.com/catcherwong/nacos-sdk-csharp/blob/8b8211df1b21c53de8246f021d77357c6c4b6e08/src/Nacos/Naming/NacosNamingClient.cs#L149-L183

**Comment by xiluzi** [comment]
> 
> 
> code 10200 问题已经调整过来了。
> 
> https://github.com/catcherwong/nacos-sdk-csharp/blob/8b8211df1b21c53de8246f021d77357c6c4b6e08/src/Nacos/Naming/NacosNamingClient.cs#L149-L183

实在不好意思。经过我昨天的排查，我发现关键不是返回的不同（官方文档里说返回的是ok，结果现在返回的是这个）。而是上面说的，NACOS1.1.4 --》NACOS1.2.0版本 ，版本更新，导致了偶尔会断。
然后我当时判断，怀疑是nacos1.2.0的bug。于是去官方仓库的issue里搜
https://github.com/alibaba/nacos/issues?q=1.2.0
结果发现了这个同样的问题。
https://github.com/alibaba/nacos/issues/2533
最终在上面的链接里找到了答案。
用第三方借助openapi实现的心跳发送的时候，且nacos是1.2.0时，要带上clusterName参数(尽管官方文档里没提到，尽管官方文档里没提到，尽管官方文档里没提到，重要的事情说3次)。不加的话，就会导致尽管一直发心跳，但仍然会偶尔断开的情况。

解决方法:
1. 如果还想继续使用nacos1.2.0。就必须发心跳时，带上clusterName参数
2. 如果不想带这参数（毕竟这参数不是必填的），那就升级到nacos1.2.1（按照官方released的说法，是已经修复了这个bug了：https://github.com/alibaba/nacos/releases/tag/1.2.1）
