### ISSUE TITLE
支持System.Text.Json

### ISSUE THREAD

**Issue by leyou240** [catcherwong/nacos-sdk-csharp#11]
如题，是否支持此方式序列化。
1、替换json.net
2、配置一个开关来提供给用户选择哪种方式
3、抽象出一个单独的包，用户选择引用不同的序列化包

请问有相关规划吗？
如果有，我可以参与贡献~

**Comment by catcherwong** [comment]
@leyou240 谢谢您对这个项目感兴趣！

规划暂时还没有，如果有这个需求，可以把序列化那一块抽一个接口出来，搭配不同的实现。
