### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by zhan520g** [catcherwong/nacos-sdk-csharp#12]
![image](https://user-images.githubusercontent.com/22271449/79429781-95343680-7ffa-11ea-9226-65a3a3c0ae53.png)

这里可能为空, 所以需要加个问号判断

**Comment by catcherwong** [comment]
@zhan520g 谢谢您对这个项目感兴趣！

可以提个RP过来的哟 😄

**Comment by zhan520g** [comment]
要的
