### ISSUE TITLE
什么时候可以支持服务分组呢？

### ISSUE THREAD

**Issue by Kalen2** [catcherwong/nacos-sdk-csharp#18]

**Comment by catcherwong** [comment]
@Kalen2 谢谢您对这个项目感兴趣！

不确定您说的服务分组具体指的是什么。

如果说的是下图的分组，那么是一直都支持的，有个GroupName的参数。

![image](https://user-images.githubusercontent.com/8394988/82636961-5e26f580-9c36-11ea-81d1-cfef6e191dec.png)

**Comment by Kalen2** [comment]
ok.是的
