### ISSUE TITLE
ServerFeatures为空

### ISSUE THREAD

**Issue by lfcbs** [catcherwong/nacos-sdk-csharp#2]
您好~我创建项目之后启动之后ServerFeatures为空，大神知道这是什么原因吗，net core版本是2.2
![微信截图_20190919091402](https://user-images.githubusercontent.com/18097343/65203575-f7a57280-dabd-11e9-8100-345da83a50d6.png)

**Comment by catcherwong** [comment]
@lfcbs  Thanks for your interest in this project.

Please follow this issue.

https://github.com/catcherwong-archive/2019/issues/2

**Comment by lfcbs** [comment]
@catcherwong Problem solved! Thank you!
