### ISSUE TITLE
大佬,元数据里面内容可以添加吗,我想带上版本号

### ISSUE THREAD

**Issue by zhan520g** [catcherwong/nacos-sdk-csharp#21]
![image](https://user-images.githubusercontent.com/22271449/83985776-fdedbe80-a96c-11ea-9494-c477f1f6d344.png)

**Comment by zhan520g** [comment]
![image](https://user-images.githubusercontent.com/22271449/83985794-12ca5200-a96d-11ea-95aa-5159bed346e1.png)

**Comment by zhan520g** [comment]
就是每个服务里面的服务详情,会有元数据展示,但是一直没内容

**Comment by zhan520g** [comment]
我增加了,怎么提交给你,好像没权限

**Comment by zhan520g** [comment]
你建个分支?

**Comment by zhan520g** [comment]
提交了,看看呢

**Comment by catcherwong** [comment]
合并了 😄

**Comment by catcherwong** [comment]
发布了  v0.2.7-alpha8
