### ISSUE TITLE
请问一下,这种方式服务名为什么省略了

### ISSUE THREAD

**Issue by zhan520g** [catcherwong/nacos-sdk-csharp#25]
![image](https://user-images.githubusercontent.com/22271449/84368360-0c0b3b80-ac08-11ea-87ca-f37c0ce56d47.png)

**Comment by zhan520g** [comment]
我现在准备去掉json文件

**Comment by zhan520g** [comment]
按照目前的情况, nacos的不同地址还只能放在json文件里,然后通过configuration获取,然后注册自己的服务上去

**Comment by zhan520g** [comment]
扩展了一个方法,麻烦有时间看看

**Comment by zhan520g** [comment]
![image](https://user-images.githubusercontent.com/22271449/84561099-2403cc00-ad7c-11ea-860b-ba05a0000bc1.png)

**Comment by catcherwong** [comment]
@zhan520g  谢谢您对这个项目感兴趣！

第一个图，应该是截的配置那里的。服务注册和发现的是

```json
"nacos": {
    "ServerAddresses": [ "http://localhost:8848" ],
    "DefaultTimeOut": 15000,
    "Namespace": "",
    "ListenInterval": 1000,
    "ServiceName": "App1"
  }
```

> 我现在准备去掉json文件

去掉json文件，具体是什么样的？是想把服务注册和发现的内容放在配置中心里面吗？还是其他？

**Comment by catcherwong** [comment]
看了一下你的PR，你是想直接通过编码的方式来配置相关参数吗？

**Comment by zhan520g** [comment]
是的，我们项目java组都是基于nacos进行配置修改处理，所以我也需要把配置文件放在nacos里面，这样的话，json配置文件可以放弃了。

**Comment by catcherwong** [comment]
了解

**Comment by catcherwong** [comment]
v0.2.7-alpha9
