### ISSUE TITLE
如何注册到非默认命名空间

### ISSUE THREAD

**Issue by PettyHandSome** [catcherwong/nacos-sdk-csharp#30]
"nacos": {
    "ServerAddresses": [ "localhost:8080" ],
    "DefaultTimeOut": 15,
    "Namespace": "5c324412-**********-a3eb7f5cf0a8",
    "ListenInterval": 1000,
    "ServiceName": "LogService",
    "Weight": 10
  },

**Comment by catcherwong** [comment]
@PettyHandSome  谢谢您对这个项目感兴趣！

**Namespace**  不为空，就不会注册到默认的public命名空间。
