### ISSUE TITLE
发送实例心跳 是否缺少名命空间字段

### ISSUE THREAD

**Issue by tingli1991** [catcherwong/nacos-sdk-csharp#5]
如果没有名命空间字段的话，那么所有的服务在发送心跳的时候将全部被归集到public下面

**Comment by catcherwong** [comment]
@tingli1991 Thanks for your interest in this project.

v0.2.1 supports `namespaceid`. 

cc https://github.com/catcherwong/nacos-sdk-csharp/commit/872e20195ecbe725319229370f988bbeb0b61af7
