### ISSUE TITLE
监听服务变化

### ISSUE THREAD

**Issue by leyou240** [catcherwong/nacos-sdk-csharp#6]
如题，请问如何监听服务变化？例如服务A有多台机器提供相关服务。我在服务扩容缩容的时候，希望nacos能检测到。请问如何实现？

**Comment by catcherwong** [comment]
如果你是直接用 `nacos-sdk-csharp-unofficial.AspNetCore`  这个包，理论上是自动处理的。如果是新增一个服务实例，那么它一定会往nacos注册。如果是减少一个服务实例，那么关掉这个服务的时候也应当会自动注销。

纯SDK目前还没有加入监听naming变化的API。不过看到其他sdk已经有了，后面应该会加上。

**Comment by leyou240** [comment]
好的，能否提供一下思路。我有时间的话，可以贡献一下相关功能

**Comment by catcherwong** [comment]
这个也是要参考其他SDK的实现，目前他们的Open-API文档并没有包含这部分内容。

**Comment by leyou240** [comment]
感觉还是和配置监听一样，设定一个时间去定时查询

**Comment by catcherwong** [comment]
大致看了一下其他sdk的实现，类似这个意思，但又不完全是定时查询去更新本地的。
