### ISSUE TITLE
Nuget上版本没更新吗

### ISSUE THREAD

**Issue by zhan520g** [catcherwong/nacos-sdk-csharp#8]
https://github.com/catcherwong/nacos-sdk-csharp/issues/7#issue-569313828

之前提的问题，  源码编译去执行不报错， nuget里面的包 不行呢， 是不是得发版了

**Comment by catcherwong** [comment]
@zhan520g  谢谢您的关注。

nuget包有段时间没更新了 ，最近这段时间再整合.NET Core自带的配置系统，近期会整合更新到nuget。

**Comment by catcherwong** [comment]
已发布0.2.5版本。

**Comment by zhan520g** [comment]
> 已发布0.2.5版本。

好的
